name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # Runs every hour, on the hour.
    # - cron: '0 * * * *'
    # Run every 5 minutes.
    # - cron: '*/5 * * * *'
    # At the beginning of every day.
    - cron: "0 0 * * *"
permissions:
  # To write the generated contents to the README.
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull in leimao.github.io articles
        uses: leimao/blog-post-workflow@v1
        with:
          feed_list: "https://leimao.github.io/feed.xml"
          max_post_count: 8
